apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
    eu-west-1: clustername
  name: mysql
spec:
  replicas: {{.Values.replicadbCount}}
  selector:
    matchLabels:
      app: backend
      eu-west-1: clustername
  template:
    metadata:
      labels:
        app: backend
        eu-west-1: clustername
    spec:
      volumes:
      - name: mysqlpod-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql
        image: mysql:5.7
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlpod-pvc
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mrp
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mu
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mp
