apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.wppvcStorage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/wpdata"
